#!/usr/local/bin/fish

alias acs='apt-cache search' # To search for packages to install
alias be='bundle exec'
alias dc='docker-compose'
alias dr='docker run'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gdmb='git diff --merge-base'
alias gdw='git diff --word-diff'
alias gg='git grep'
alias gl='git log'
alias glp='git log -p'
alias gp='git fetch --prune origin && git pull --rebase && git submodule update --init --recursive'
alias gpfo='git push --force origin'
alias gpo='git push origin'
alias gs='git status'
alias k='kubectl'
alias ll='ls -l'
if test (uname) = "Linux"
  alias pbcopy='xclip -selection clipboard'
end
alias sa='ssh-add -t 8h'
alias terraform='tofu'
alias tfip='tofu init -upgrade && tofu plan -lock=false'
alias vim='nvim'
