alias be='bundle exec'
alias gpl='git pull --rebase && git submodule update --init --recursive'
alias gst='git status'
alias sa='ssh-add -t $((8*3600))'
alias spek='spec -f nested -c -b '
alias trt='touch tmp/restart.txt'
