#!/bin/bash

# Submodules
git submodule init && git submodule update

# Homebrew
if [ "$(uname)" == "Darwin" ]; then
  if ! [ -x "$(command -v brew)" ]; then
    echo "Please install homebrew."
    exit 1
  fi
  brew bundle
fi

# Shell
cp aliases "$HOME"/.aliases
cp shrc "$HOME"/.config/fish/config.fish

# Linux gnome-terminal padding
if [ "$(uname)" == "Linux" ]; then
  mkdir -p ~/.config/gtk-3.0
  cp gtk.css ~/.config/gtk-3.0/gtk.css
fi

# GNU Screen
cp screenrc "$HOME"/.screenrc

# Git
cp gitattributes ~/.gitattributes
cp gitignore "$HOME"/.gitignore
GIT_EMAIL=$(git config --global --get user.email)
export GIT_EMAIL
if [ -z "$GIT_EMAIL" ]; then
  read -r -p "Email for Git: " email
  export GIT_EMAIL=$email
fi
GIT_SIGNINGKEY=$(git config --global --get user.signingkey)
export GIT_SIGNINGKEY
if [ -z "$GIT_SIGNINGKEY" ]; then
  read -r -p "Signing Key for Git: " signingkey
  GIT_SIGNINGKEY=$signingkey
  export GIT_SIGNINGKEY
fi
eval echo "\"$(cat gitconfig.template)\"" > "$HOME"/.gitconfig

# Ruby
cp gemrc "$HOME"/.gemrc

# Vim
mkdir -p "$HOME"/.vimswap
cp vimrc "$HOME"/.vimrc

#   ...plugins
mkdir -p ~/.vim/pack/plugins/start
#   symlink my vendored submodules into the vim packages system
find dotvim/vendor -maxdepth 1 -mindepth 1 -type d | while read -r dir; do
  symlink="$(basename "$dir")"
  if [ ! -e ~/.vim/pack/plugins/start/"$symlink" ]; then
    ln -s "$PWD/$dir" ~/.vim/pack/plugins/start/"$symlink"
  fi
done

# Ubuntu configuration
. /etc/lsb-release
if [ "$DISTRIB_ID" == "Ubuntu" ]; then
  echo ansible-playbook ubuntu.yaml -K
fi

echo "Your dotfiles have been copied to $HOME"
