#!/bin/zsh

# Brew bundle
if ! [ -x "$(command -v brew)" ]; then
  echo "Please install homebrew"
  exit 1
fi
brew bundle

# Submodules
git submodule init && git submodule update

# GNU Screen
cp screenrc     $HOME/.screenrc

# Zsh
cp aliases $HOME/.aliases
cp zshrc $HOME/.zshrc

# Git
export GIT_EMAIL=`git config --global --get user.email`
if [ -z "$GIT_EMAIL" ]; then
  read -p "Email for Git: " email
  export GIT_EMAIL=$email
fi
export GIT_SIGNINGKEY=`git config --global --get user.signingkey`
if [ -z "$GIT_SIGNINGKEY" ]; then
  read -p "Signing Key for Git: " signingkey
  export GIT_SIGNINGKEY=$signingkey
fi
eval echo "\"$(cat gitconfig.template)\"" > $HOME/.gitconfig
cp gitignore    $HOME/.gitignore

# Ruby
cp gemrc        $HOME/.gemrc

# Vim
mkdir -p        $HOME/.vimswap
cp vimrc        $HOME/.vimrc

#   ...plugins
declare -a folders=("after" "compiler" "indent" "ftdetect" "ftplugin" "syntax")
for folder in "${folders[@]}"
do
  mkdir -p $HOME/.vim/$folder
  cp -R dotvim/vendor/*/$folder/* $HOME/.vim/$folder
done

echo "Your dotfiles have been copied to $HOME"
