#!/bin/bash

# Submodules
git submodule init && git submodule update

if [ "$(uname)" == "Darwin" ]; then
  # Brew bundle
  if ! [ -x "$(command -v brew)" ]; then
    echo "Please install homebrew"
    exit 1
  fi
  brew bundle
fi

# GNU Screen
cp screenrc "$HOME"/.screenrc

# Shell
cp aliases "$HOME"/.aliases
cp shrc "$HOME"/.config/fish/config.fish

# Git
GIT_EMAIL=$(git config --global --get user.email)
export GIT_EMAIL
if [ -z "$GIT_EMAIL" ]; then
  read -r -p "Email for Git: " email
  export GIT_EMAIL=$email
fi
GIT_SIGNINGKEY=$(git config --global --get user.signingkey)
export GIT_SIGNINGKEY
if [ -z "$GIT_SIGNINGKEY" ]; then
  read -r -p "Signing Key for Git: " signingkey
  GIT_SIGNINGKEY=$signingkey
  export GIT_SIGNINGKEY
fi
eval echo "\"$(cat gitconfig.template)\"" > "$HOME"/.gitconfig
cp gitignore "$HOME"/.gitignore

# Ruby
cp gemrc "$HOME"/.gemrc

# Vim
mkdir -p "$HOME"/.vimswap
cp vimrc "$HOME"/.vimrc

#   ...plugins
declare -a folders=("after" "compiler" "indent" "ftdetect" "ftplugin" "syntax")
for folder in "${folders[@]}"
do
  mkdir -p "$HOME"/.vim/"$folder"
  cp -R dotvim/vendor/*/"$folder"/* "$HOME"/.vim/"$folder"
done

echo "Your dotfiles have been copied to $HOME"
