add_newline = false

format = """
$kubernetes\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$cmd_duration\
$jobs\
$status\
$character
"""

[cmd_duration]
format = '\[[$duration]($style)\] '

[kubernetes]
disabled = false
# display in square brackets instead
format = '\[[$symbol$context( \($namespace\))]($style)\] '
style = "blue"

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 2

[git_branch]
format = '[$symbol$branch]($style) '

[git_commit]
tag_disabled = false

[hostname]
format = '[$hostname$ssh_symbol]($style)'

[python]
format = '[$symbol(\($virtualenv\) )]($style) '

[username]
format = '[$user]($style)@'
