- name: Ubuntu
  become: yes
  hosts: localhost
  connection: local
  vars_prompt:
  - name: "user"
    prompt: "Enter the username to configure"
    private: no

  tasks:
  - ansible.builtin.package_facts: manager=apt

  - name: Configure Nodesoource repository
    ansible.builtin.shell:
      creates: /etc/apt/sources.list.d/nodesource.list
      cmd: curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    register: nodesource_repo

  - name: Repositories
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
      update_cache: no
    register: repositories
    with_items:
    - ppa:neovim-ppa/unstable

  - name: Packages
    ansible.builtin.apt:
      install_recommends: no
      update_cache: "{{ nodesource_repo.changed or repositories.changed }}"
      name:
      - curl
      - fish
      - graphviz
      - neovim
      - nodejs
      - screen
      - shellcheck
      - xclip

  - name: Configure Shell
    ansible.builtin.user:
      name: "{{ user }}"
      shell: /usr/bin/fish
      state: present

  - name: Install starship
    ansible.builtin.shell:
      creates: /usr/local/bin/starship
      cmd: curl -sS https://starship.rs/install.sh | sh -s -- -y
