- name: Ubuntu
  become: yes
  hosts: localhost
  connection: local

  tasks:
  - name: Keys
    ansible.builtin.apt_key:
      url: "{{ item.url }}"
      keyring: "{{ item.keyring }}"
      state: present
    with_items:
    - name: signal
      keyring: /usr/share/keyrings/signal-desktop-keyring.gpg
      url: https://updates.signal.org/desktop/apt/keys.asc
    - name: spotify
      keyring: /etc/apt/trusted.gpg.d/spotify.gpg
      url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    - name: regolith
      keyring: /usr/share/keyrings/regolith-archive-keyring.gpg
      url: https://regolith-desktop.org/regolith.key

  - name: Remove old repository
    ansible.builtin.apt_repository:
      repo: ppa:regolith-linux/release
      state: absent

  - name: Repositories
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
      update_cache: no
    register: repositories
    with_items:
    - deb [arch=amd64] https://regolith-desktop.org/release-ubuntu-focal-amd64 focal main
    - deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
    - deb http://repository.spotify.com stable non-free
    - ppa:system76-dev/stable

  - name: Packages
    ansible.builtin.apt:
      update_cache: "{{ repositories.changed }}"
      name:
      - caffeine
      - chromium-browser
      - fish
      - gnome-tweaks
      - graphviz
      - regolith-desktop
      # ...
      - i3xrocks-app-launcher
      - i3xrocks-battery
      - i3xrocks-focused-window-name
      - i3xrocks-info
      - i3xrocks-memory
      - i3xrocks-rofication
      - regolith-compositor-picom-glx
      # ... end regolith
      - screen
      - shellcheck
      - signal-desktop
      - spotify-client
      - system76-power # battery life
      - tlp            # battery life
      - variety
      - vim-gtk # for +clipboard support
      - xclip

  - name: Shell
    ansible.builtin.user:
      name: robin
      shell: /usr/bin/fish
      state: present

  - name: Xresources
    ansible.builtin.file:
      dest: /home/robin/.config/regolith2
      state: directory
      owner: robin
      group: robin

  - name: Regolith Xresources
    ansible.builtin.copy:
      src: files/Xresources
      dest: /home/robin/.config/regolith2/Xresources
      owner: robin
      group: robin
