- name: Ubuntu
  become: yes
  hosts: localhost
  connection: local

  tasks:
  - ansible.builtin.package_facts: manager=apt

  - name: Repositories
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
      update_cache: no
    register: repositories
    with_items:
    - ppa:neovim-ppa/unstable

  - name: Packages
    ansible.builtin.apt:
      install_recommends: no
      update_cache: "{{ repositories.changed }}"
      name:
      - curl
      - fish
      - graphviz
      - neovim
      - screen
      - shellcheck
      - xclip

  - name: Configure Shell
    ansible.builtin.user:
      name: ubuntu
      shell: /usr/bin/fish
      state: present

  - name: Install starship
    ansible.builtin.shell:
      creates: /usr/local/bin/starship
      cmd: curl -sS https://starship.rs/install.sh | sh -s -- -y
